---
title: "Descriptive analysis"
author: "Cole Tanigawa-Lau"
date: ''
output:
  html_document:
    theme: paper
    df_print: paged
    toc: yes
    toc_depth: 3
    toc_float: yes
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 7, fig.height = 5)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r about, echo=FALSE, results = "asis"}
cat(
  sprintf("Updated: %s.", 
          format(Sys.time(), "%b %d, %Y at %H:%M:%S", usetz = TRUE)),
  sprintf("Working directory: `%s`.", getwd()),
  sep = "\n\n"
)
```


Reads:

  - data/mod_RF_absolute.rds

Writes:

  - FILEPATH

# Setup

```{r packages, warning=FALSE, message=FALSE}
library(coler)
library(dplyr)
library(data.table)
library(caret)
library(randomForest)

```

```{r final prep, child = "0-final_prep.Rmd"}
stopifnot(exists("absolute"))
```

```{r}
models <- readRDS("data/fitted_models.rds")
```


# Balance
```{r}
cobalt::bal.tab(absolute[ , ..vars_absolute], treatment = absolute$closed)

baltests <- absolute[ , map(.SD, ~ t.test(.x ~ closed, .SD) %>% list()), 
                      .SDcols = vars_absolute]

balDT <- 
  map(baltests, ~ .x[[1]] %>% broom::tidy()) %>% 
  rbindlist(idcol = "variable")

# estimate: estimate1 - estimate2 = treatment - control
setnames(balDT, c("estimate1", "estimate2"), c("mean_closed", "mean_open"))
```


```{r results = "asis"}
round_num <- function(data, func = round, digits = 3){
  num_test <- vapply(data, is.numeric, logical(1))
  num_cols <- names(which(num_test))
  
  out <- dplyr::mutate_at(data, num_cols, func, digits = digits)
  
  return(out)
}

balDT[order(-abs(statistic))] %>% 
  round_num(func = signif, digits = 3) %>% 
  knitr::kable()
```


# K-Means
```{r}
kmeans_absolute <- kmeans(absolute[ , ..vars_absolute], centers = 2)
absolute[ , kluster := as.factor(kmeans_absolute$cluster - 1)]

absolute[ , confusionMatrix(kluster, reference = closed, positive = "1")]
```

# Logit
## Coefficients
### Fit model on standardized data
```{r}
absolute_std <- copy(absolute)
set_cols(absolute_std, j = vars_absolute, FUN = scale)

models$logit.absolute.std <- 
  glm(formula = form_absolute, family = binomial(link = "logit"), 
      data = absolute_std)
```


```{r results = "asis"}
stargazer::stargazer(models$logit.absolute, models$logit.absolute.std,
                     type = "html", column.labels = c("raw", "standardized"))
```

## Confusion matrix: fitted values
```{r}
confusionMatrix(
  
  models$logit.absolute$fitted.values %>% 
    cutoff(., threshold = median(.)),
  
  reference = absolute$closed,
  
  positive = "1"
)
```


# Random forest

```{r}
models$RF.absolute$importance %>% 
  as_tibble(rownames = "variable") %>% 
  arrange(-MeanDecreaseAccuracy)
```


## Confusion matrix
### Fitted values

```{r}
# Fitted
confusionMatrix(predict(models$RF.absolute, newdata = absolute),
  
  reference = absolute$closed,
  
  positive = "1")
```

### OOB predictions
```{r}
# OOB prediction
confusionMatrix(models$RF.absolute$predicted,
  
  reference = absolute$closed,
  
  positive = "1")
```

# Out-of-sample prediction
Terrible. Zero true positives.

```{r eval = FALSE, include = FALSE}
set.seed(575)
test <- sample_frac(absolute, 0.20)
train <- setdiff(absolute, test)
```

```{r eval = FALSE, include = FALSE}
## FAILS TO PREDICT ANY CLOSURES IN TEST SET

logit <- glm(data = train, formula = form_absolute, family = binomial(link = "logit"))

test[ , caret::confusionMatrix(closed, 
                               predict(logit, newdata = test, type = "response") %>% 
                                 {as.numeric(. > 0.5)} %>% as.factor())]$table

predict(logit, newdata = test, type = "response") %>% 
                                 {as.numeric(. > 0.5)} %>% table()
```

```{r eval = FALSE, include = FALSE}
mtries <- 3:8
mods <- 
  parallel::mclapply(mtries,
                     FUN = function(mtry) 
                       randomForest(x = train[ , ..vars_absolute],
                                    y = train[ , closed], mtry = mtry),
                     mc.cores = length(mtries))

map(mods, ~ test[ , caret::confusionMatrix(closed, predict(.x, newdata = test))]$table) %>% 
  setNames(mtries)
```



